# Generated by Django 5.0.6 on 2025-04-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('hardness', models.FloatField()),
                ('solids', models.FloatField()),
                ('chloramines', models.FloatField()),
                ('sulfate', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('prediction', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Water Quality Prediction',
                'verbose_name_plural': 'Water Quality Predictions',
            },
        ),
    ]
